apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: capargo
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - "*"
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusters
  verbs:
  - get
  - list
  - watch
