apiVersion: apps/v1
kind: Deployment
metadata:
  name: capargo
spec:
  replicas: 1
  selector: {}
  template:
    spec:
      containers:
      - name: capargo
        resources:
          limits:
            cpu: 500m
            memory: 1G
      serviceAccount: capargo
      securityContext:
        runAsUser: 1001
