apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: capargo
namespace: capargo
resources:
- namespace.yaml
- deployment.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- serviceaccount.yaml
