apiVersion: apps/v1
kind: Deployment
metadata:
  name: capargo
spec:
  selector: {}
  template:
    spec:
      containers:
      - name: capargo
        args:
          - --argo-namespace=argocd
          - --cluster-namespace=vcluster
          - --zap-log-level=4
        image: localhost:5001/superorbital/capargo:local
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 250m
            memory: 500M
