name: Release assets

on:
  release:
    types:
      - published

permissions:
  contents: read

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Build manifests
        run: hack/release-manifests.sh ${{ github.event.release.tag_name }}

      - name: Release manifests
        uses: softprops/action-gh-release@v2
        with:
          files: |
            _output/install.yaml
